.gitignore, actions.yaml, src/charm.py, src/literals.py, src/utils.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_password_rotation.py, tests/integration/test_provider.py, tests/integration/test_scaling.py
This PR adds an action to change the password of an operator related user.
The charm sends the user change to zookeeper and then stores the new password on the application databag.
- Added actions to set passwords.
- `charm.py`:
- Added password rotation action handler
- Added some extra helpers for integration tests.
Added an integration test for password rotation.
=> Add password rotation action

src/charm.py, src/config.py, tests/unit/test_config.py
- Update to align with other database charm relation interfaces, after ZooKeeper change
=> chore: switch to tls flag over ssl

.github/workflows/ci.yaml
Avoid a long-running integration test in case of failing gatekeeping tests. It will slightly increase the complete tests scope runtime but will save (a lot?) of electricity/money for Canonical as often new pull requests have some initial typos/issues to be polished.
=> DPE-781 Run integration tests for passed lint/unit tests only (#51)

src/charm.py, src/config.py, src/provider.py, tests/integration/helpers.py, tests/integration/test_provider.py, tests/unit/test_config.py
This PR addresses Jira ticket [DPE-661](https://warthogs.atlassian.net/browse/DPE-661).
Updates relation info on peer-related events.
Adds a call on `config_changed` event that updates related application info, if they exist.
- `src/charm.py`: _on_config_changed_ now updates provider info.
- `src/config.py`: _bootstrap_server_ will change the port depending on TLS status.
- `src/provider.py`: added a method to update information on related applications.
Added a test on the provider-suite to check connection information.
=> fix: Update relation endpoints

src/charm.py, src/config.py
Linked to Jira [DPE-660](https://warthogs.atlassian.net/browse/DPE-660).
Changes `sync_password` to be stored using the `set_secret`/`get_secret` placeholders.
Note: Information coming from Zookeeper relation is not stored using the same scheme.
=> chore: Password to use secret placeholders

lib/charms/zookeeper/v0/client.py, src/auth.py, src/charm.py, src/config.py, src/provider.py, src/snap.py, src/tls.py, tests/unit/test_auth.py, tests/unit/test_charm.py, tests/unit/test_config.py, tests/unit/test_provider.py, tests/unit/test_snap.py, tox.ini
- As ZK charm no-longer uses the `kafka_snap` lib, there is little value in it
- Moved code to `src/snap.py`
- Added various unit-tests, especially to `provider` and `charm`, which did not have any before
- All unit-tests now use `pytest` framework
- It's OK to pass this flag, as does nothing if not TLS
=> test: add/update unit-tests to use pytest throughout

charmcraft.yaml, metadata.yaml, requirements.txt, src/charm.py, src/config.py, tests/integration/app-charm/charmcraft.yaml, tests/integration/test_charm.py, tests/integration/test_password_rotation.py, tests/integration/test_provider.py, tests/integration/test_scaling.py, tests/integration/test_tls.py, tests/unit/test_charm.py, tests/unit/test_config.py, tox.ini
- Blocks and does not start if < minimum:range storages found
- More gracefully handle storage adding/removing/attach/detach events for currently running charm. Currently none handled
- Integration tests for all storage events
- This is not added to this PR as to 'generate' logs to these mounted storage directories, we have to build a robust `producer` so that topic metadata is stored across these dirs
- This hasn't been done yet, TBC
- NOTE - All future PR's will be merging to feature branch `feat/storage` to keep PRs more reviewable.
=> feat: add basic Juju storage support

.github/workflows/ci.yaml, .github/workflows/release.yaml, metadata.yaml, src/charm.py, tests/integration/app-charm/metadata.yaml, tests/integration/app-charm/src/charm.py, tests/integration/client.py, tests/unit/test_charm.py, tests/unit/test_provider.py, tox.ini
- `feat: added conditional logging + status messages during storage events`
- Adding/Removing storage is fairly destructive and will require manual intervention from an administrator to return cluster to a healthy state 
- `feat: rolling-restart units during storage events`
- Needed to actually update kafka service to use new `log.dirs` 
- `feat: set storage range to allow for 1 storage only`
- This will be used in development
- `style: use parameterized context managers in unittests`
- Aesthetic preference
=> chore: enable useful status/logging messages for storage

lib/charms/operator_libs_linux/v1/snap.py, lib/charms/rolling_ops/v0/rollingops.py, src/charm.py, src/snap.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/unit/test_charm.py, tox.ini
- This is needed as new storage mounts aren't found by the snap, even with plug `removable-devices`. This is likely a bug, but am unable to resolve without this workaround
=> feat: disable+enable snap service on storage events

.github/workflows/ci.yaml, .github/workflows/release.yaml, charmcraft.yaml, lib/charms/operator_libs_linux/v1/snap.py, lib/charms/rolling_ops/v0/rollingops.py, metadata.yaml, requirements.txt, src/charm.py, src/config.py, src/snap.py, tests/integration/app-charm/charmcraft.yaml, tests/integration/app-charm/metadata.yaml, tests/integration/app-charm/src/charm.py, tests/integration/client.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_password_rotation.py, tests/integration/test_provider.py, tests/integration/test_scaling.py, tests/integration/test_tls.py, tests/unit/test_charm.py, tests/unit/test_config.py, tests/unit/test_provider.py, tox.ini
- By default supports 1+ storage volumes. A 10G storage volume will be installed by default for `log.dirs`
- When storage is added or removed, the Kafka service will restart to ensure it uses the new volumes
- When storage is added or removed, log + charm status messages will prompt users to manually reassign partitions so that the new storage volumes are populated. By default, Kafka will not assign partitions to new directories/units until existing topic partitions are assigned to it, or a new topic is created
=> feat: add storage support

pyproject.toml, src/charm.py, src/config.py, src/provider.py, src/tls.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_password_rotation.py, tests/integration/test_provider.py, tests/integration/test_scaling.py, tests/integration/test_tls.py, tests/unit/test_auth.py, tests/unit/test_charm.py, tests/unit/test_config.py, tests/unit/test_snap.py, tox.ini
- Use `callback_override` to ensure that storage restarts use state lock
- Avoids multiple units restarting at the same time
- It's possible that after a restart a broker will be in an error state. Checking broker-active fixes that
- Has side-effect of slowing down rolling-ops due to potential retries on `broker_active`
=> fix: add rolling storage events, add restart status

config.yaml, pyproject.toml, src/charm.py, src/config.py, src/literals.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/unit/test_config.py
Addresses [DPE-1061](https://warthogs.atlassian.net/browse/DPE-1061).
Listeners are now split into two categories, INTERNAL and EXTERNAL. Both can still be used normally, but the external listener allows for a custom advertised listener, so Kafka clients on external networks can resolve the hostname.
[DPE-1061]: https://warthogs.atlassian.net/browse/DPE-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Split internal and external listeners

README.md, actions.yaml, src/auth.py, src/charm.py, src/config.py, src/literals.py, src/provider.py, src/tls.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_provider.py, tests/unit/test_charm.py, tests/unit/test_config.py
- This is to address the confusing purpose mentioned below
- As inter-broker SCRAM before cluster init, the charm must make an authenticated API call to ZooKeeper, and again at cluster init
- JAAS file contains credentials needed to authenticate, and path is written to `/etc/environment` so that it is recognized by `snap start kafka` command 
- Kafka ships with `bin/*.sh` commands to do various administrative tasks. All the Kafka documentation points to these scripts to get started
- Up until now, our JAAS/SCRAM/auth setup made it challenging for a user to run any administrative actions from some admin client. This was because:
- JAAS file was confusing, unclear what it was for
- `KAFKA_OPTS` env-var pointing to the JAAS file was hidden
- Commands would only work with `--zookeeper` as the …
=> feat: add admin user, improve administrator command UX

pyproject.toml, src/charm.py, src/config.py, src/provider.py, src/tls.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_provider.py, tests/integration/test_scaling.py, tests/integration/test_tls.py, tests/unit/test_auth.py, tests/unit/test_config.py, tests/unit/test_snap.py
Specifies source directories for ruff so imports are split following Python patterns.
=> Fix Ruff import sorting

.github/workflows/ci.yaml, tests/integration/conftest.py, tests/integration/test_charm.py, tests/integration/test_password_rotation.py, tests/integration/test_provider.py, tests/integration/test_scaling.py, tests/integration/test_tls.py
Before this PR only the tester charm `app_charm` had a fixture. This PR adds a fixture for kafka itself.
Drive-by fixes:
- Auto-cancel concurrent workflows
- Charm's path type hint [is Path](https://github.com/charmed-kubernetes/pytest-operator/blob/257eec333092a31231a66bb7e6683ac265fe48e2/pytest_operator/plugin.py#L897) (not PosixPath)
=> Add itest fixture for kafka itself

src/charm.py, src/tls.py, tests/integration/test_provider.py, tests/integration/test_scaling.py, tests/integration/test_tls.py
- Without this change, `juju debug-log` was inundated with `0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.`
- In case no files exist to `rm`, add `-f` flag to avoid error
- Addresses https://github.com/canonical/kafka-operator/issues/66
- Getting model timeout errors for slow CI deploy. Longer timeouts helps this
- Changes made in https://github.com/canonical/zookeeper-operator/pull/47 means that Kafka will `idle` until the next `update-status` triggers ZK to complete the relation. Longer idle periods helps this
- Addresses https://github.com/canonical/kafka-operator/issues/73
=> fix: various flakey CI tests, error handling and logging warnings

.github/workflows/release.yaml
I have noticed that our release pipelines was erroring out because of a typo, and therefore we did not publish new charm recently because of this :(
Unfortunately to test if this would work we need to merge this PR
=> [MISC] Fix typo in release pipeline

metadata.yaml
- Updating the `charmcraft.yaml` to include `issues:` **should** fix this iirc
- If not, still a good change
=> fix: point charmhub buttons to this repo

config.yaml, lib/charms/tls_certificates_interface/v1/tls_certificates.py, metadata.yaml, src/config.py, src/literals.py, src/structured_config.py, src/tls.py, tests/integration/app-charm/actions.yaml, tests/integration/app-charm/lib/charms/operator_libs_linux/v0/apt.py, tests/integration/app-charm/lib/charms/operator_libs_linux/v1/snap.py, tests/integration/app-charm/src/charm.py, tests/integration/app-charm/src/utils.py, tests/integration/helpers.py, tests/integration/test_provider.py, tests/integration/test_tls.py, tests/unit/test_config.py, tests/unit/test_tls.py, tox.ini
Addresses [DPE-1339](https://warthogs.atlassian.net/browse/DPE-1339).
Two relation names have been added:
- `trusted-certificates`
- `trusted-ca`
They implement the _requirer_ side of tls-certificates-interface. These relations will hold one certificate, that will be imported into the truststore of each broker. When a relation is removed, the certificate is deleted from the truststores.
A new listener is added when the relations are in use: `CLIENT_SSL` on port `9094`
[DPE-1339]: https://warthogs.atlassian.net/browse/DPE-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature: mTLS

config.yaml, src/structured_config.py, tests/unit/test_config.py
Addresses [DPE-1340](https://warthogs.atlassian.net/browse/DPE-1340)
Adds [`ssl.principal.mapping.rules`](https://kafka.apache.org/documentation/#brokerconfigs_ssl.principal.mapping.rules) config option to charm.
[DPE-1340]: https://warthogs.atlassian.net/browse/DPE-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add regex rules config option

.github/workflows/ci.yaml, metadata.yaml, poetry.lock, pyproject.toml, src/auth.py, src/charm.py, src/config.py, src/literals.py, src/provider.py, src/snap.py, src/tls.py, src/utils.py, tests/integration/app-charm/src/charm.py, tests/integration/app-charm/src/utils.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_tls.py, tests/unit/test_auth.py, tests/unit/test_charm.py, tests/unit/test_config.py, tests/unit/test_snap.py, tox.ini
Blocked by https://github.com/canonical/charmed-kafka-snap/pull/22
Unblocks https://github.com/canonical/kafka-operator/pull/89
- Writing files now requires one to change ownership to `snap_daemon` user so that it can be accessed from the main snap service
- As we're calling `keytool` and `openssl` as `root` through a subprocess, we have to make sure that `keystore.p12` and `truststore.jks` both get explicit ownership from the snap user 
- Various paths updated, see https://github.com/canonical/charmed-kafka-snap/pull/22 for more context
- Mounted storage volumes labelled `log-data` are now just `data`
- Up until now, the charm updated users + acls using `--zookeeper` as the authorizer. This is marked for deprecation
- Since the addition of `client.properties`, we can now use …
=> refactor/feat: use updated non-root snap, use `--bootstrap-server` auth

src/charm.py, src/grafana_dashboards/kafka-metrics.json, src/literals.py, src/snap.py
Addresses [DPE-1432](https://warthogs.atlassian.net/browse/DPE-1432)
Fixes some of the expressions from the dashboard to use up-to-date metrics from the JMX exporter. Most of them switch from calculating the per second value by using `rate()[1m]` on total counters to just use `persec` metric directly.
[DPE-1432]: https://warthogs.atlassian.net/browse/DPE-1432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix expressions on dashboard

src/charm.py, src/config.py, src/snap.py, tests/unit/test_charm.py, tests/unit/test_snap.py
- This wasn't enabled before due to bug in TLS lib
- Should work out the box now
- Issue would happen when charm didn't set up fast enough before `update-status` fired, raising unhandled `KeyError`
=> feat: enable hostname_verification for ZooKeeper, handle noPIDfound

tests/integration/app-charm/actions.yaml, tests/integration/app-charm/src/charm.py, tests/integration/helpers.py, tests/integration/test_tls.py
I believe the integration tests on mTLS SHOULD not have passed as there were multiple problems I encountered when running step-by-step:
* ssl_principal_mapping_rules was not set, therefore the producer should not have had permission to write
* in order to rightfully produce message to the topic, the topic should have been created before
* broker-ca parameter is best to be first base64 encoded before being passed to the action, and then decoded in the action (similarly to what is done in the tls-certificate-operator)
I have also added an action to retrieve the offsets on the test topic, to be used in order to make sure that messages were indeed produced and pushed to Kafka. The condition for passing now should be way more stringent. 
I believe it would also be good to test that clients can …
=> [MISC] Fix integration tests

src/tls.py, tests/integration/app-charm/actions.yaml, tests/integration/app-charm/src/charm.py, tests/integration/test_tls.py
The issue is the logic of this check, that will return instead of continuing (needs more `not`):
```
if not self.private_key or self.keystore_password or self.truststore_password:
```
All these extra checks are forced because of pyright. But some of them are not really needed, as things that _seem_ to be `None` in `operator` are actually initialized later on.
Rationale for the changes:
- Checking that the private keys and password exists doesn't really provide any information, the same can be achieved by just checking that the `tls` flag exists (`self.enabled`) 
- I don't know of a situation where `event` doesn't have an `event.relation` attached to it. It is initialized on all relation events: https://github.com/canonical/operator/blob/main/ops/charm.py#L435-L446
=> fix: rework mtls checks

config.yaml, src/config.py, src/tls.py, tests/unit/test_config.py
- https://warthogs.atlassian.net/browse/DPE-1985
- https://warthogs.atlassian.net/browse/DPE-1987
- https://warthogs.atlassian.net/browse/DPE-1986
=> fix: ensure config changed called on trusted-changed

config.yaml, src/config.py, src/health.py, src/literals.py, src/structured_config.py, tests/unit/test_config.py, tests/unit/test_health.py
- Set to 6GB using default `profile=production` config option. Otherwise 1GB.
- Health check looks for available memory, informing user if insufficient for desired profile
=> feat: add `profile` configured JVM heap args

src/charm.py, src/config.py, tests/integration/test_charm.py, tests/unit/test_config.py
The charm will figure out if `rack.properties` file exists. If it does, its contents will be added to `server.properties`.
Since there are no relations being triggered, `update_status` has been used to also check if the file was created after everything went `active | idle`. An alternative approach could be to add an action to manually trigger the check.
There are no integration tests yet, since the rack awareness charm hasn't been released.
=> [DPE-1905] Add rack awareness integration

src/alert_rules/prometheus/jmx_missing.rule, src/alert_rules/prometheus/jvm_filling.rule, src/alert_rules/prometheus/kafka_metrics.rules
This PR is to provide some sensible defaults for the base alerting rules for Kafka
Note: The label `juju_charm!=".*"` in every rule is to workaround a bug currently found in COS, where the `juju_charm` is applied to the rules but not to the metrics. See more details [here](https://github.com/canonical/grafana-agent-k8s-operator/issues/190)
=> [DPE-2012] Alerting rules for Kafka VM

src/auth.py, src/provider.py
Addresses #104
- Change `current_acls` in `auth.py` to a property
- Added a method to iterate over relations to remove users. Not used, where to invoke? `update_status`?
- Change access to peer databag on `provider.py`
=> [DPE-1921] Handle delete_user exception

src/utils.py, tests/unit/test_utils.py
backported from zookeeper-operator [#74](https://github.com/canonical/zookeeper-operator/pull/74)
=> Fix invalid /etc/environment (fix #119)

README.md
Looking at the stats for charmhub in Google Analytics, we noticed that we have no referrals from GitHub for our Kafka, Kafka-k8s and Spark charms. So It would be good to link to the charmhub pages of the charms. This is a big missed opportunity as a huge amount of referrals for Canonical are generated via Github.
=> [DPE-2285] Refer Charmhub space from Github README.md

config.yaml, src/structured_config.py, src/tls.py, tests/unit/test_tls.py
Adds config option to specify extra sans.
- A new property on `tls.py` has been added that parses the contents of `certificate_extra_sans`.
- Config option uses `{unit}` placeholder and replaces it with the unit number.
- Removed `peer_relation` property from `KafkaTLS`, to use `charm.peer_relation` instead.
=> [DPE-2195] Add `certificate_extra_sans` config option

.github/workflows/ci.yaml, docs/how-to/h-create-mtls-client-credentials.md, src/literals.py, src/snap.py, src/tls.py, tests/integration/app-charm/lib/charms/operator_libs_linux/v1/snap.py, tests/integration/app-charm/src/charm.py, tests/integration/test_provider.py, tests/integration/test_tls.py
Depends on https://github.com/canonical/charmed-kafka-snap/pull/27
- Was originally installed to use `keytool`
- Now usable through `charmed-kafka.keytool`
=> DPE-1965 - chore: use keytool snap app

.github/workflows/ci.yaml, src/charm.py, src/config.py, src/health.py, tests/integration/ha/ha_helpers.py, tests/integration/ha/test_ha.py
Adds network cut, which includes an IP change to the unit.
- Broker won't rejoin the cluster until the next `update_status` triggers.
=> [DPE-2644] Test: network cut

.github/workflows/ci.yaml
- Ensures only one test runs at any time, avoiding CPU limit / timeouts etc
- Pytest Operator cleanup was challenging after the LXD model was messed with during HA tests
- `--keep-model` allows Github to clean up resources after test completion
=> cicd: keep model in ha test, max-parallel=1

src/literals.py
This PR is to test that the charm work well with a new snap revision that was built from source. That revision is currently sitting on `3/edge/dpe-2704-kafka-from-source`
=> [DPE-2704] Integrate Kafka built from source

src/grafana_dashboards/kafka-metrics.json
Both kafka and kafka-k8s charms include a grafana dashboard which uses a variable $job.
This variable does not seem to add value to the monitoring capability, as it is both redundant with other filters (namely juju-model), and not configured to enable multi selection (which causes issues when we deploy a vm cluster and a k8s cluster related to the same monitoring stack).
=> [DPE-3880] Remove all instances of $job variable in dashboard

src/core/models.py, src/events/zookeeper.py, tests/integration/ha/ha_helpers.py, tests/integration/helpers.py, tests/integration/test_scaling.py, tests/integration/test_tls.py, tests/unit/conftest.py, tests/unit/test_charm.py, tests/unit/test_config.py, tests/unit/test_tls.py
This PR adds `database` and `requested-secrets` to the relation databag, while preserving the `chroot` entry for compatibility with older zookeeper charms
=> [DPE-3926] Enforce zookeeper client interface

.github/workflows/ci.yaml
Disabling sync docs for contribution outside of Canonical, such that the checks are clean, even for external contributors
=> [MISC] CI improvements

lib/charms/hydra/v0/oauth.py, metadata.yaml, src/charm.py, src/core/cluster.py, src/core/models.py, src/events/oauth.py, src/literals.py, src/managers/config.py, tests/integration/ha/ha_helpers.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_tls.py, tests/unit/test_config.py
This is the equivalent of the  PR opened on the [K8S charm](https://github.com/canonical/kafka-k8s-operator/pull/77), for adding the oauthbearer listener. 
In a few words this PR does the following:
- adds the oauth interface from hydra
- on a relation on that interface, it adds a sasl/oauthbearer listener
- it adds a unit test (using both a scram and oauthbearer client) to check if the config is generated correctly 
- the rest is about reorganizing the protocols and the mechanisms (cause it was a bit messy)
- protocols are: sasl_plain, sasl_ssl and ssl
- mechanisms are: scram-sha-512, oauthbearer, and ssl (this one makes no sense but it is for parity and it matches only with ssl as a protocol)
=> [CSS-6503] Add OAuth support for non-charmed external clients

src/core/workload.py, src/events/broker.py, src/events/zookeeper.py, src/health.py, src/managers/balancer.py, src/managers/tls.py, src/workload.py, tests/unit/test_charm.py, tests/unit/test_workload.py
This PR changes the way we pass commands to be executed by the workload. On k8s, due to pebble using `sh` by default, we cannot use commands using pipes, unless we use the `bash -c <command>`.
=> refactor: Use list of str workload.exec for k8s parity

src/charm.py, src/events/balancer.py, src/events/broker.py, src/events/tls.py, src/managers/config.py, tests/integration/test_balancer.py, tests/integration/test_provider.py, tests/unit/test_tls.py
First iteration of TLS for Cruise Control.
When Kafka - Zookeeper have tls enabled, cruise control needs updated properties to be able to maintain connection.
- TLS events are declared at `charm` level. This means that the same events are used for both roles.
- `events/tls.py` now will duplicate its calls to the managers API. One for each role.
- TLS managers are now instantiated for both broker and balancer. This is done before exiting the manager early because the events will need to trigger manager API.
- Restart for the balancer doesn't seem to go through until `update_status`
- `peer_cluster` doesn't update `bootstrap_servers` and `zookeeper_uris` when they change. This is mitigated [here](https://github.com/canonical/kafka-operator/pull/220/files#diff-168ff0fb69a03619c31bb042470b3f46 …
=> [DPE-4581] TLS

src/managers/auth.py, tests/integration/app-charm/actions.yaml, tests/integration/app-charm/config.yaml, tests/integration/app-charm/src/charm.py, tests/integration/test_provider.py, tests/unit/test_auth.py
- Related applications will be granted ACL permissions for the requested topic, as a prefix (i.e all topic names starting with th passed field
- The requirements for `topic-name` switch from `LITERAL` ACLs to `PREFIXED` ACLs are:
- 4 chars or more
- Ends with a `*` char
=> [DPE-4951] - fix: re-enable prefixed topic names during relations

src/managers/config.py
- Fixes https://github.com/canonical/kafka-operator/issues/230
- ZooKeeper ACLs are not recursive, meaning that any written data to a zNode nested under the `chroot`, will be readable by all
- Setting`zookeeper.set.acl=true` ensures that there are protections on the zNodes written by Kafka
=> [DPE-5208] - fix: secure written znodes

.github/workflows/sync_docs.yaml
The repository got to an inconsistent state where the tag was not updated to latest commit, but the content was up to date and in sync with Discourse.
I have just deleted the tags and re-triggered the automation which has created the tag at the tip of `main`. 
I have also noted that we are not using the official repository. It used to have some issues, that got fixed some months ago. In Spark we are already using the official action since a few months, with no issue. Hopefully the glitch that created the inconsistency here may have also been resolved, as a number of optimizations and improvements have been landed as well.
=> [DPE-5532] Gatekeeper failing on kafka-operator repository

src/charm.py, src/events/zookeeper.py
See https://github.com/canonical/zookeeper-operator/pull/162 for rationale and explanations.
This PR includes a quick fix for the dreaded `"blocked" == "active"` flaky CI error. I'll be working on that during this pulse and probably the next.
=> [DPE-5218] Enable compatibility with ZK restore feature

.github/workflows/ci.yaml, src/charm.py, src/core/cluster.py, src/core/models.py, src/events/balancer.py, src/events/broker.py, src/events/peer_cluster.py, src/literals.py, src/managers/auth.py, src/managers/balancer.py, src/managers/config.py, src/workload.py, tests/integration/test_kraft.py, tests/unit/scenario/test_kraft.py, tests/unit/test_charm.py, tox.ini
This PR enables KRaft to be deployed on it's own application. It also extends the `peer_cluster` interface to accommodate controller role.
------
Data flow between "controller" and "broker":
- If an application is a `controller`, write to own databag/peer_cluster the `controller-quorum-uris` as soon as possible. These uris can be set at any given time, since they only depend on IP and unit id.
- If an application is a `broker`, write to own databag/peer_cluster the `cluster-uuid` as soon as possible. At some point this will be a task for the `cluster_manager` instead of the broker.
Formatting the storage before starting the cluster is a needed step on KRaft mode:
```
charmed-kafka.storage format --cluster-id $uuid -c server.properties --add-scram …
```
=> [DPE-5501][DPE-5234] Multi app

pyproject.toml, src/managers/config.py, tests/unit/test_config.py
Changes:
- Set package mode to false in pyproject.toml. This will prevent poetry from emitting a warning every time we use the `install` subcommand
- The properties related to Cruise Control are now set only if we run the balancer workload in the application or if we use the peer-cluster relation. This will prevent the broker from spamming the logs with warnings in simple deployments
I'll keep this PR as a draft until https://github.com/canonical/kafka-operator/pull/244 is merged, as we'll need to update the relation name in the condition
=> [DPE-5611] Remove cruise-control metrics reporter if no balancer

charmcraft.yaml, config.yaml, poetry.lock, pyproject.toml, src/core/structured_config.py, tests/unit/test_config.py, tests/unit/test_kraft.py
This PR is mostly relevant for feature parity with https://github.com/canonical/kafka-k8s-operator/pull/151, but it also ports the rust toolchain upgrade improvement.
=> [DPE-5945] Rename expose_external configuration option

src/core/cluster.py, src/events/tls.py, src/managers/tls.py, tests/integration/helpers.py, tests/integration/test_tls.py
- Added **truststore dynamic reload** functionality using `kafka-configs` utility to reload truststore without broker restart
- Added integration test for truststore dynamic reload functionality
=> [DPE-5553] feat: Don't restart server on keystore/truststore updates

.github/workflows/ci.yaml, .github/workflows/release.yaml, src/events/broker.py
- This seemed to be broken, as new Charmcraft version failed rather than warned for local changes to libs, or unpublished libs (in the case of `kafka`
- Now only runs when 'scheduled', not blocking release
- This was needed for our charm to work with external clients on Prodstack
- By default, we update all the 'set' ports on `update-status` -> `config-changed` as normal, with values retrieved from all currently enabled listeners
=> feat: support juju expose by setting listener ports

src/core/structured_config.py, src/managers/config.py, tests/unit/test_config.py, tests/unit/test_structured_config.py, tests/unit/test_tls.py
- `worker-{unit}:30000` --> advertised listeners from 39092+, `worker-0` TLS certificate DN
- `{unit}-foo.com` --> `0-foo.com` TLS certificate DN
- `bananarama.party` --> `bananarama.party` TLS certificate DN
=> [DPE-6636] - feat: support non-unit/port extra_listeners

src/core/models.py, tests/integration/test_kraft.py
This PR fixes a `RelationDataAccessError` bug occurred in KRaft multi-mode on broker side during scale-out. 
-  KRaft multi-mode, broker-side scale-out results in error state. https://github.com/canonical/kafka-operator/issues/305
=> [DPE-6547] fix: KRaft multi-mode scaling bug on broker side

src/alert_rules/prometheus/kafka_metrics.rules, src/grafana_dashboards/kafka-metrics.json
backport of #252 that landed on `3/stable`
=> [DPE-5702] chore: Active Controllers alert set to == 0 (#252)

README.md
Update the badge to show status from ReadTheDocs build for the `main` branch.
=> chore: Update the documentation badge in README

docs/conf.py
Fix the product link in RTD docs header -- the link was broken due to "https://" prefix which apparently doesn't work correctly in the current Starter pack.
=> Fix the product link in RTD docs header

docs/reference/index.md
Update link in our documentation that must be specific to the track 3 of the product.
=> Update docs links for track 3

README.md
This PR overhauls the README with major changes in Juju ecosystem, and after Kafka 4:
- Removes zookeeper refs
- Password rotation is now done using secrets
- All `run-action`s are now `run`
- All `relate`s are now `integrate`
=> docs: Update README.md for Kafka 4

.github/workflows/sync-to-k8s.yml
If we don't have a synced baseline for both repos this workflow will keep failing, so make manual instead for the time being to stop failures on the PRs
=> Make sync manual

.github/workflows/ci.yaml, src/charm.py, src/core/cluster.py, src/core/models.py, src/core/workload.py, src/events/broker.py, src/events/peer_cluster.py, src/events/tls.py, src/managers/auth.py, src/managers/config.py, src/managers/controller.py, src/managers/tls.py, src/workload.py, tests/integration/conftest.py, tests/integration/ha/continuous_writes.py, tests/integration/helpers/__init__.py, tests/integration/helpers/ha.py, tests/integration/helpers/pytest_operator.py, tests/integration/test_kraft.py, tests/integration/test_tls.py, tests/integration/test_tls_complex.py, tests/unit/conftest.py, tests/unit/test_tls_manager.py, tests/unit/test_workload.py, tox.ini
Fixes https://github.com/canonical/kafka-operator/issues/343
The process is as follows:
- Each unit reports its trusted certificates in its own unit databag, which is updated after restart
- Leader units report the intersection of trusted certificates of all units via app databag in the `peer-cluster` relation
- When a CA rotation is happening in either side, the app first waits for the other side (remote app) to report new cert being added to their truststores (which means a complete rolling restart in the remote app). In case both apps are in the middle of a rotation, the BROKER side attempts to restart first.
- After the remote side finishes rolling restart and reports the new cert in their truststore, the local app will start its rolling restart.
- Both apps will keep both old and new …
=> [DPE-7522] feat: add HA during CA rotation

src/core/cluster.py, src/core/models.py, src/events/peer_cluster.py, tests/unit/test_tls_manager.py
This PR fixes a [possibly] race condition issue in `RelationState.update` and the underlying `data_interfaces` logic, which in some cases leads to secrets not being set, for example **when a user immediately relates broker and controller after deployment**.
The only material change in this PR is [these lines](https://github.com/canonical/kafka-operator/pull/387/files#diff-e46c88bb687d77b94764a732b3e08a0a7bd544a64e606429c0b787c13e1c226aR124-R131) added to the `update` method of `RelationState`. The other changes were basically refactoring some of the code from `cluster` to the `models` module, which seemed more appropriate.
To test this PR, the following script was run before and after changes. 
- Before the changes, almost half of the deployments led to broker being stuck in `waiting for …
=> [DPE-7846] fix: secrets not set issue in RelationState.update

src/core/cluster.py, src/core/models.py, src/events/broker.py, src/events/provider.py, src/events/tls.py, src/events/user_secrets.py, src/health.py, src/managers/tls.py, tests/unit/conftest.py, tests/unit/test_charm.py, tests/unit/test_provider.py
- Fixes https://github.com/canonical/kafka-operator/issues/397
- [Fixes](https://github.com/canonical/kafka-operator/pull/399/commits/d3d0bd407c160714a87dd645aa7c9fdd0a5ba2f4) the issue of `AuthManager` and `KafkaHealth` failing too slowly if broker/controller are not up, leading to deferral back pressure...
- Fixes the issue of `config-changed` calls linearly increasing with the number of clients, which makes cluster convergence to `active|idle` really slow
=> [DPE-7987] fix: race condition in internal TLS setup

docs/conf.py
Uncommented and populated the slug parameter in config to fix 404 page rendering on documentation.ubuntu.com
=> docs: Hotifx for docs 404 page rendering

docs/explanation/security.md
This PR fixes a broken link in `explanation/security.md`
=> docs: change broken link in security.md

docs/conf.py, docs/explanation/security.md, docs/redirects.txt, docs/requirements.txt
Implementing page-to-page matching to apply after wildcard redirects.
You can check them by navigating to the preview build URLs:
Test 1:
https://canonical-ubuntu-documentation-library--405.com.readthedocs.build/charmed-kafka/405/t-relate-kafka/ 
should redirect to 
https://canonical-ubuntu-documentation-library--405.com.readthedocs.build/charmed-kafka/405/tutorial/integrate-with-client-applications/index.html
Test 2:
https://canonical-ubuntu-documentation-library--405.com.readthedocs.build/charmed-kafka/405/h-deploy-azure/
should redirect to
https://canonical-ubuntu-documentation-library--405.com.readthedocs.build/charmed-kafka/405/how-to/deploy/deploy-azure/index.html
=> Implement page-to-page Discourse redirects

.github/workflows/ci.yaml
This PR removes `lib-check` from the CI.
Rationale:
- `lib-check` always fails on this repo given the fact that we have an unpublished charmlib, producing no meaningful results
- Leads to lots of failure noise on scheduled tests.
=> ci: remove lib-check

README.md
Fixed the docs badge in our README file to show correct results by replacing the version slug with the correct one for the track `3`.
I've switched to the default (flat) style, as it seems to be looking closer to other badges. To see a preview, open the rendered README file. For example: https://github.com/canonical/kafka-operator/blob/32293af7cf373f82d4ebc33706da24470f8556f9/README.md
=> Docs: Fix docs badge in readme

docs/how-to/deploy/deploy-anywhere.md, docs/index.md
Replaced Charmhub links in the Kafka-K8s substrate warnings with Kafka K8s RTD docs links.
=> docs: Replace charmhub links
