config.yaml
lib/charms/kafka/v0/kafka_snap.py

- `docs: update and document KafkaSnap lib after ZK changes`
- `chore: remove old config file`

docs: update KafkaSnap lib based on ZK work

---

.github/workflows/release.yaml

Adds auto release to charmhub.
Token added to repository secrets.

Added auto-release to charmhub

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
src/charm.py
tests/integration/app-charm/src/charm.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/integration/test_kafka_provider.py
tox.ini

- `fix: updated failing tests after resolution of charmcraft bug` - See [juju deploy bug](https://bugs.launchpad.net/snapstore-server/+bug/1981579)
- `chore: split test + release ci`

test: update failing int tests

---

charmcraft.yaml
lib/charms/kafka/v0/kafka_snap.py
lib/charms/tls_certificates_interface/v1/tls_certificates.py
lib/charms/zookeeper/v0/client.py
metadata.yaml
requirements.txt

Nothing to review. This just updates `zookeeper` and `kafka` libs, and adds `tls_certificates_interface` to the repo.

Add and update needed libs to project

---

src/auth.py
src/charm.py
src/config.py

Updates the code with the changes made on the k8s TLS pr.

Add pull request feedback from k8s

---

actions.yaml
src/charm.py

feat: add action to rolling restart unit

---

tox.ini

because of issue 23 on pyproject-flake8

[MISC] pyproject-flake8 restriction to <6.0.0 

---

lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/observability_libs/v0/juju_topology.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
metadata.yaml
src/charm.py
src/grafana_dashboards/node-exporter-full.json
src/snap.py

Addresses [DPE-1017](https://warthogs.atlassian.net/browse/DPE-1017)
Add [node_exporter](https://snapcraft.io/node-exporter) snap and a [dashboard](https://grafana.com/grafana/dashboards/1860-node-exporter-full/) to integrate with COS.
Libs and dashboard.json don't need review.

Integrate with COS

---

lib/charms/tls_certificates_interface/v1/tls_certificates.py
src/config.py
src/tls.py

- Fixes bug with how sans were being used
- Sans containing host DNS, host IP
- Subject name of host IP
Focus review on commits 34f1c95faa97c30f75078f443a3de81cf431e4ab and 317610b2b59d8806845662eadd5900eabacdf55f to save headache of tls lib updates

feat: working zookeeper and client hostname verification

---

README.md
actions.yaml
charmcraft.yaml
config.yaml
metadata.yaml

Addresses [DPE-1011](https://warthogs.atlassian.net/browse/DPE-1011).
Update and restructure of the README to follow current documentation guidelines.
- A section with COS integration will be added once [the open PR](https://github.com/canonical/kafka-operator/pull/60) is merged.
[DPE-1011]: https://warthogs.atlassian.net/browse/DPE-1011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve readme

---

tests/integration/test_provider.py
tests/integration/test_tls.py

This PR will fix the tests with TLS.

Fix tls test

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
CONTRIBUTING.md
pyproject.toml
tests/integration/__init__.py
tests/integration/conftest.py
tests/integration/test_charm.py
tests/integration/test_password_rotation.py
tests/integration/test_provider.py
tests/integration/test_scaling.py
tests/integration/test_tls.py
tests/unit/__init__.py
tox.ini

Ported from https://github.com/canonical/mysql-k8s-operator/pull/146

Cache charmcraft pack container, skip unstable tests except on schedule 

---

lib/charms/data_platform_libs/v0/data_interfaces.py
src/provider.py
tests/integration/app-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
tests/integration/app-charm/src/charm.py
tests/integration/helpers.py
tests/integration/test_provider.py
tests/unit/test_provider.py

Addresses [DPE-1342](https://warthogs.atlassian.net/browse/DPE-1342).
[DPE-1342]: https://warthogs.atlassian.net/browse/DPE-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set of consumer-prefix-group from relation data

---

lib/charms/operator_libs_linux/v1/snap.py
src/snap.py

Addresses [DPE-834](https://warthogs.atlassian.net/browse/DPE-834).
After install, snaps will hold refreshes.
[DPE-834]: https://warthogs.atlassian.net/browse/DPE-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add hold forever to snaps

---

src/config.py
src/utils.py
tests/integration/test_charm.py
tests/unit/test_utils.py

Blocked by https://github.com/canonical/zookeeper-operator/pull/62

fix: allow multiple apps to write safely to etc/environment

---

actions.yaml
lib/charms/data_platform_libs/v0/upgrade.py
lib/charms/zookeeper/v0/client.py
metadata.yaml
src/charm.py
src/config.py
src/literals.py
src/snap.py
src/upgrade.py
src/utils.py
tests/unit/test_charm.py
tests/unit/test_config.py
tests/unit/test_upgrade.py

* add kafka upgrade
* add zk check
* update client lib

[DPE-2242] Add kafka upgrade (#120)

---

.github/workflows/ci.yaml
src/literals.py
tests/integration/helpers.py
tests/integration/test_upgrade.py
tox.ini

Based on [Zookeeper upgrade test](https://github.com/canonical/zookeeper-operator/pull/78)

[DPE-2314] Add upgrade integration test

---

docs/how-to/h-upgrade.md
docs/index.md

Adding documentation about charm upgrade feature (How-To)

[DPE-2446] How-to Upgrade Documentation

---

.github/workflows/ci.yaml
lib/charms/kafka/v0/client.py
src/charm.py
src/health.py
tests/integration/ha/continuous_writes.py
tests/integration/ha/ha_helpers.py
tests/integration/ha/test_ha.py

Add network cut without IP change

[DPE-2370] Test: network throttle

---

src/literals.py

The revision is a test revision published from https://github.com/canonical/charmed-kafka-snap/pull/32

[DPE-2702] Update Kafka version to 3.6.0

---

.github/workflows/release.yaml
src/charm.py

Also adds full signature on Manager classes (leftover from refactor comments)

chore: Update release.yaml

---

src/charm.py
src/core/workload.py
src/literals.py
src/managers/config.py
src/workload.py
tests/integration/helpers.py
tests/integration/test_balancer.py
tests/unit/test_config.py

[DPE-4502] Add base CC JMX integration and extend COS

---

actions.yaml
src/events/balancer.py
src/literals.py
src/managers/balancer.py
tests/integration/test_balancer.py
tests/integration/test_provider.py
tests/integration/test_tls.py
tests/unit/test_balancer.py

See https://github.com/canonical/kafka-k8s-operator/pull/122
This PR also addresses the red CI on the CC feature branch by pinning the self-signed-cert charm to rev 163

[DPE-4952] Feat/add remove brokers

---

src/charm.py
src/core/cluster.py
src/core/models.py
src/core/workload.py
src/events/broker.py
src/literals.py
src/managers/auth.py
src/managers/config.py
src/workload.py

Initial milestone to have a co-located Kafka in KRaft mode. General fixes will be addressed on upcoming PRs. Description for the whole feature can be viewed on #232

[DPE-5114][DPE-5118] Colocated controller-broker

---

src/core/cluster.py
src/core/models.py
src/core/structured_config.py
src/events/balancer.py
src/events/broker.py
src/events/tls.py
src/events/zookeeper.py
src/managers/config.py
src/managers/tls.py
tests/unit/test_kraft.py

- This is required for using some cloud storages, and Ceph

[DPE-5826] - fix: remove lost+found from new storages

---

src/core/cluster.py
src/core/models.py
src/events/broker.py
src/events/peer_cluster.py
src/literals.py
src/managers/config.py
tests/integration/test_kraft.py

- Added controller user
- Added SCRAM authentication for controller/broker authentication

[DPE-5349] feat: Add internal user and SASL/SCRAM authentication

---

.github/workflows/ci.yaml
tests/integration/helpers.py
tests/integration/test_password_rotation.py
tests/integration/test_tls.py

[DPE-6247] - test/cicd: stabalise int-test ci

---

.github/tics_run_sh_ghaction_test.yml

This PR extends our current CI to do checks and push to TIOBE dashboard.

Add TIOBE to CI

---

src/core/structured_config.py
tests/unit/test_structured_config.py

Updates config values and constraints for Kafka 4.0 based on [KIP-1030](https://cwiki.apache.org/confluence/display/KAFKA/KIP-1030%3A+Change+constraints+and+default+values+for+various+configurations)

[DPE-7142] Update configs

---

docs/reference/release-notes/revision-156-126.md
docs/reference/release-notes/revision-156-136.md
docs/reference/release-notes/revision-195-149.md
docs/reference/release-notes/revision-205.md

Rewrite release notes with the new format

New release notes format implemented 

---

.github/workflows/sync-to-k8s.yml

Test automatic syncing of feature PRs to kafka-k8s-operator.

[PoC] Sync to k8s

---

.github/pull_request_template.md

Our goal is to aim a simple checklist for PRs: 1 checkbox for docs and another one for cloud resources.
The last part is a mandatory requirement from top management and was specifically requested by Mykola.

Add pull request template with a checklist

---

docs/conf.py
docs/explanation/cryptography.md
docs/tutorial/cleanup.md
docs/tutorial/deploy.md
docs/tutorial/integrate-with-client-applications.md
docs/tutorial/use-kafka-connect.md

Replaced the `juju status --watch` with `watch juju status`.
Added color for UX: `watch -c juju status --color`.

docs: Replace juju status --watch with watch juju status

---

src/events/broker.py
src/events/tls.py
src/managers/config.py

Refactor of `config_changed` to move relevant logic to the tls events and config manager modules.

[DPE-7839] Refactor config changed
